config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'inscricao' => 'welcome#enrollment'
  get 'visitacao' => 'welcome#visitation'
  get 'visitacao/feedback' => 'welcome#visitation_feedback'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController; end

app/helpers/application_helper.rb
module ApplicationHelper; end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>jovens da Paz</title>

  <meta name="description" content="Pastoral jovens da paz da paróquia Nossa Senhora da Paz de Ipanema - EJC - Encontro de Jovens com Cristo da Igreja Católica" property="og:description">
  <meta name="keywords" content="jovens da paz, ejc, encontro de jovens com cristo, cristo, católica, igreja, jovens, grupo jovem, encontro de jovens, pastoral, católico, nossa senhora da paz, ipanema, encontro jovem, caridade, comida no prato, animando corações, pequena semente">

  <!-- OpenGraph Tags -->
  <meta property="og:title" content="jovens da Paz" />
  <meta property="og:site_name" content="jovens da Paz" />
  <meta property="og:url" content="http://www.jovensdapaz.com.br" />
  <meta property="og:image" itemprop="image" content="<%= image_path('menu/logo-social-medias.png') %>" />

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- Custom Fonts -->
  <!--   <link href="assets/font-awesome.css" rel="stylesheet"> -->
  <link href='http://fonts.googleapis.com/css?family=Raleway:100,600' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300' rel='stylesheet' type='text/css'>

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <script>
      document.createElement('video');
    </script>
  <![endif]-->

</head>
<body id="home" class="parallax-page">

<%= yield %>

</body>
</html>

app/views/welcome/_about_us.html.erb
<!-- About Section -->
<section id="about" class="about content-section alt-bg-light" style="background-color: #2cb1be;">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <h2 style="color: #fff;">Quem Somos</h2>
        <p style="color: #fff;">Somos jovens brasileiros, que moram no Rio de Janeiro, que têm sonhos, aspirações, desafios, problemas como qualquer jovem da nossa idade. A diferença está que escolhemos seguir pela estrada da vida acompanhados de um grande amigo: Jesus Cristo. Esta nossa decisão, baseada na nossa Fé, nos une e nos faz servir e viver experiências únicas em vários campos da nossa vida, especialmente na nossa Paróquia Nossa Senhora da Paz.</p>
        <p style="color: #fff;">Juntos, somos a Pastoral ‘Jovens da Paz’, uma rede de jovens católicos que a partir de uma paróquia em Ipanema, busca com muitas ideias, energia e vontade, construir uma sociedade mais cheia de amor, respeito, conhecimento, paz e conectada com Deus.</p>
        <p style="color: #fff;">Nascemos oficialmente em Março de 2016, como a consequência de um legado de mais de 30 anos de diversas obras envolvendo jovens, na Nossa Senhora da Paz. Somos mais de 1.000 pessoas, servindo, aprendendo e vivendo, juntos, a Igreja de Cristo.</p>
      </div><!-- /.col-md-6 -->
      <div class="col-md-6">
        <!-- Display image -->
        <img src="<%= image_path('background/about.png')%>" class="img-responsive">
        <!-- Optional video embed code -->
        <!-- <div class="embed-responsive embed-responsive-16by9"> -->
          <!-- <iframe src="https://player.vimeo.com/video/132613118?title=0&amp;byline=0&amp;portrait=1" class="embed-responsive-item" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe> -->
        <!-- </div> -->
      </div><!-- /.col-md-6 -->
    </div><!-- /.row -->
  </div><!-- /.container -->
</section><!-- /.section -->

app/views/welcome/_footer.html.erb
<!-- Footer -->
<footer id="footer">
  <div class="container">
    <div class="row text-center">
      <div class="col-md-12 segment">
        <a href="#" title="Hallooou - HTML5 Template">
          <h2>
            Gostou? Então fale conosco!
          </h2>
        </a>
        <p class="white">Adoramos conhecer pessoas novas, para conversar, ouvir e ajudar.<br/>Assim como também gostamos de conhecer organizações parceiras<br/>que possam apoiar a nossa causa enquanto pastoral.</p>
        <p class="white"><b>Endereço</b>: Rua Visconde de Pirajá, 339, Ipanema.<br/>
        Rio de Janeiro, RJ</p>
      </div><!-- /.col-md-12 -->
    </div><!-- /.row -->
    <div class="row text-center">
      <div class="col-md-12 social segment">
        <h4>Conecte-se</h4>
        <a href="https://www.instagram.com/jovensdapaz" title="Instagram" target="_blank">
          <img src="<%= image_path('footer/instagram-icon-min.png')%>" style="display: inline-table;" class="img-responsive">
          <p>Instagram: @jovensdapaz</p>
        </a>
        <a href="#footer" title="Snapchat">
          <img src="<%= image_path('footer/snapchat-icon-min.png')%>" style="display: inline-table;" class="img-responsive">
          <p>Snapchat: jovensdapaz</p>
        </a>
        <a href="#footer" title="Spotify">
          <img src="<%= image_path('footer/spotify-icon-min.png')%>" style="display: inline-table;" class="img-responsive">
          <p>Spotify: jovensdapaz</p>
        </a>
        <a href="https://www.facebook.com/ejcpazipanema" title="Facebook" target="_blank">
          <img src="<%= image_path('footer/facebook-icon-min.png')%>" style="display: inline-table;" class="img-responsive">
          <p>Facebook: /jovensdapaz</p>
        </a>
      </div><!-- /.col-md-12 -->
    </div><!-- /.row -->
  </div><!-- /.container -->
  <div class="copynote">
    <div class="container">
      <div class="row">
        <div class="col-md-12 text-center">
          &copy; 2015. Paróquia Nossa Senhora da Paz.
        </div><!-- /.col-md-12 -->
      </div><!-- /.row -->
    </div><!-- /.container -->
  </div><!-- /.copynote -->
  <div class="nav pull-right scroll-top">
    <a href="#home" title="Scroll to top"><i class="fa fa-angle-up"></i></a>
  </div>
</footer><!-- /.footer -->

app/views/welcome/_menu.html.erb
<!-- Navigation -->
<nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header pull-left">
      <a class="navbar-brand page-scroll" href="#page-top">
        <!-- replace with your brand logo/text -->
        <span class="brand-logo">
          <!-- <%#= image_tag "logo.svg" %> -->
          <img src="<%= image_path('menu/logo.png')%>" alt="Jovens da Paz" title="Jovens da Paz" class="img-responsive">
        </span>
      </a>
    </div>
    <div class="main-nav pull-right">
      <div class="button_container toggle">
        <span class="top"></span>
        <span class="middle"></span>
        <span class="bottom"></span>
      </div>
    </div>
    <div class="overlay" id="overlay">
      <nav class="overlay-menu">
        <ul>
          <li><a href="#about">Quem Somos</a></li>
          <li><a href="#missions">Missões - Inscrição EJC</a></li>
          <li><a href="#counter">Somai e Multiplicai</a></li>
          <li><a href="#protector">Nosso Patrono</a></li>
          <li><a href="#parish">Nossa Paróquia</a></li>
          <li><a href="#sponsors">Nossos Parceiros</a></li>
          <!-- <li><a href="#testimonials">Depoimentos</a></li> -->
          <li><a href="#footer">Fale Conosco</a></li>
        </ul>
      </nav>
    </div>
  </div><!-- /.container -->
</nav>

app/views/welcome/_missions.html.erb
<!-- Services Section -->
<section id="missions" class="services content-section" style="background-color: #ec1968;">
  <div class="container">
    <div class="row text-center">
      <div class="col-md-12">
        <h2 style="color: #fff;">Missões e Iniciativas de Transformação</h2>
      </div><!-- /.col-md-12 -->
      <div class="container">
        <div class="row" style="margin-bottom: 15px;">
          <div class="col-md-3">
            <img src="<%= image_path('mission/animando-coracoes-branco.png')%>" class="img-responsive">
          </div><!-- /.col-md-3 -->
          <div class="col-md-3">
            <img src="<%= image_path('mission/jovens-no-cantagalo-branco.png')%>" class="img-responsive">
          </div><!-- /.col-md-3 -->
          <div class="col-md-3">
            <img src="<%= image_path('mission/coral-dos-jovens-branco.png')%>" class="img-responsive">
          </div><!-- /.col-md-3 -->
          <div class="col-md-3">
            <img src="<%= image_path('mission/pequena-semente-branco.png')%>" class="img-responsive">
          </div><!-- /.col-md-3 -->
        </div><!-- /.row -->
        <div class="row" style="margin-bottom: 15px;">
          <div class="col-md-3 col-md-offset-1">
            <img src="<%= image_path('mission/sao-tomas-de-aquino-branco.png')%>" class="img-responsive">
          </div><!-- /.col-md-3 col-md-offset-1 -->
          <div class="col-md-3">
            <img src="<%= image_path('mission/terco-dos-jovens-branco.png')%>" class="img-responsive">
          </div><!-- /.col-md-3 -->
          <div class="col-md-4">
            <img src="<%= image_path('mission/comida-no-prato-branco.png')%>" class="img-responsive">
          </div><!-- /.col-md-4 -->
        </div><!-- /.row -->
        <div class="row text-center">
          <div class="col-md-12">
            <div class="circle">
              <div class="number">75º</div>
              <div class="text">EJC</div>
            </div>
            <h3 class="caption white">Encontro de Jovens com Cristo</h3>
            <div class="col-md-9">
              <p style="color: #fff; text-align: left;">Um grande mergulho no infinito interior, este evento é um retiro de 2 dias conduzido por jovens cheios de amor e fé. Muito especial e cheio de boas surpresas, é uma experiência única que há 30 anos conecta jovens com a sua espiritualidade.</p>
              <p style="color: #fff; text-align: left;">
                <b>Quando:</b> 23 e 24 de Novembro de 2019<br/>
                <b>Aonde acontece:</b> Colégio São Paulo, Ipanema - RJ
              </p>
            </div><!-- /.col-md-9 -->
            <div class="col-md-3">
              <%= link_to 'Inscreva-se', inscricao_path, class: 'btn btn-overcolor', style: 'background-color: #ec1968; vertical-align: middle; margin-top: 70px;' %>
            </div><!-- /.col-md-3 -->
          </div><!-- /.col-md-12 -->
        </div><!-- /.row -->
      </div><!-- /.container -->
    </div><!-- /.row -->
  </div><!-- /.container -->
</section><!-- /.section -->

app/views/welcome/_parish.html.erb
<!-- About Section -->
<section id="parish" class="about content-section alt-bg-light" style="background-color: #2cb1be;">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <h2 style="color: #fff;">Paróquia Nossa Senhora da Paz</h2>
        <p style="color: #fff;">A Paróquia Nossa Senhora da Paz, fica localizada na Rua Visconde de Pirajá, esquina com a rua Joana Angélica, em Ipanema, dando nome à Praça que fica bem à sua frente.</p>
        <p style="color: #fff;">Fundada há quase 100 anos e reconhecida pela comunidade carioca pelas suas obras, tem tradição em seu movimento com jovens, que vêm de todo o Rio participar das missas, eventos e servir em suas pastorais.</p>
        <p style="color: #fff;">Na Igreja, os ‘Jovens da Paz’ cuidam da <b>Missa de Domingo às 19h30min</b>, celebrada pelo Pe. Jorjão. (Se você nunca foi, estamos lhe esperando de braços abertos!)</p>
        <p style="color: #fff;">Além da pastoral jovem, nossa Paróquia tem mais de 50 pastorais!</p>
        <p style="color: #fff;">Caso queira saber mais sobre 'a Paz', <a href="http://www.nspaz.org.br/indexs.htm" title="Paróquia Nossa Senhora da Paz - RJ" target="_blank">clique aqui</a></p>
      </div><!-- /.col-md-6 -->
      <div class="col-md-6">
        <!-- Display image -->
        <img src="<%= image_path('background/paroquia.png')%>" class="img-responsive">
        <!-- Optional video embed code -->
        <!-- <div class="embed-responsive embed-responsive-16by9"> -->
          <!-- <iframe src="https://player.vimeo.com/video/132613118?title=0&amp;byline=0&amp;portrait=1" class="embed-responsive-item" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe> -->
        <!-- </div> -->
      </div><!-- /.col-md-6 -->
    </div><!-- /.row -->
  </div><!-- /.container -->
</section><!-- /.section -->

app/views/welcome/_protector.html.erb
<!-- About Section -->
<section id="protector" class="about content-section alt-bg-light">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <h2>Nosso Patrono Guido Schäffer</h2>
        <h5>O surfista, médico e seminarista que é nossa inspiração</h5>
        <p>“Jesus is my wave!”. Essa é a vibe e inspiração que temos a partir do Guido, que participou das missões jovens da nossa Paróquia ainda em vida e foi um exemplo enorme de amor à Eucaristia e de vida em profunda oração.</p>
        <p>Médico, seminarista, surfista e um ser humano que se dedicou aos pobres doentes, à conversão de outros jovens afastados do Pai, morto em 2009 e que apenas 6 anos depois foi proclamado pelo Papa Francisco como Servo de Deus, o primeiro passo para o seu reconhecimento como o 1º Santo Jovem Católico Brasileiro.</p>
      </div><!-- /.col-md-6 -->
      <div class="col-md-6">
        <!-- Display image -->
        <img src="<%= image_path('background/guido.png')%>" class="img-responsive">
        <!-- Optional video embed code -->
        <!-- <div class="embed-responsive embed-responsive-16by9"> -->
          <!-- <iframe src="https://player.vimeo.com/video/132613118?title=0&amp;byline=0&amp;portrait=1" class="embed-responsive-item" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe> -->
        <!-- </div> -->
      </div><!-- /.col-md-6 -->
    </div><!-- /.row -->
  </div><!-- /.container -->
</section><!-- /.section -->

app/views/welcome/_sponsors.html.erb
<!-- Our clients -->
<section id="sponsors" class="our-clients content-section text-center">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2>Nossos parceiros</h2>
        <h3 class="caption white">Eles chegaram junto apoiando e deixando ainda mais forte a nossa causa e ajudam a levar mais fé e alegria para os jovens.</h3>
      </div><!-- /.col-md-12-->
    </div><!-- /.row -->
    <div class="row client-slider">
      <div class="item col-xs-4 col-md-2 i">
        <a href="http://www.zonasulatende.com.br" title="Supermercado Zona Sul" target="_blank">
          <img src="<%= image_path('sponsors/zona-sul-icon.png') %>" class="img-responsive">
        </a>
      </div><!-- /.col-xs-4 -->
      <div class="item col-xs-4 col-md-2 i">
        <a href="http://www.sorvetealex.com.br" title="Sorvete Alex" target="_blank">
          <img src="<%= image_path('sponsors/sorvete-alex-icon.png') %>" class="img-responsive">
        </a>
      </div><!-- /.col-xs-4 -->
      <div class="item col-xs-4 col-md-2 i">
        <a href="http://radioibiza.com.br" title="Rádio Ibiza" target="_blank">
          <img src="<%= image_path('sponsors/radio-ibiza-icon.png') %>" class="img-responsive">
        </a>
      </div><!-- /.col-xs-4 -->
      <div class="item col-xs-4 col-md-2 i">
        <a href="http://csprio.com.br" title="Colégio São Paulo - RJ" target="_blank">
          <img src="<%= image_path('sponsors/csp-icon.png') %>" class="img-responsive">
        </a>
      </div><!-- /.col-xs-4 -->
    </div><!-- /.row -->
  </div><!-- /.container -->
</section><!-- /.our-clients -->

app/views/welcome/_testimonials.html.erb
<!-- Testimonials Section -->
<section id="testimonials" class="testimonials content-section" style="background-color: #28b24b;">
  <div class="container">
    <div class="row text-center">
      <div class="col-md-12">
        <h2 style="color: #fff;">O que dizem nossos membros</h2>
        <h3 class="caption gray" style="color: #fff;">Veja o depoimento de alguns jovens que fazem parte da pastoral Jovens da Paz.</h3>
      </div><!-- /.col-md-12 -->
      <div class="container">
        <div class="row">
          <div class="col-md-8 col-md-offset-2">
            <div class="client-testimonials owl-carousel owl-theme">
              <div class="item">
                <p class="speech">Eu só pude ver a beleza da Igreja, de fato, depois que fiz o EJC. A partir dele, criei vínculo com outros jovens e encontrei uma nova forma de me relacionar com Deus e com as pessoas.</p>
                <div class="client-info">
                  <img src="<%= image_path('testimonial/lucas-icon.png') %>" />
                  <h4 style="color: #fff;">Lucas Kobbaz, 22 anos</h4>
                  <span style="color: #fff;">Estudante de Medicina</span>
                </div>
              </div><!-- /.item -->
              <div class="item">
                <p class="speech">Fazer parte do grupo de jovens da Nossa Senhora da Paz mudou completamente a minha vida. Eu era um cara sem fé nenhuma e a partir da minha decisão de 'entrar', muita coisa na minha vida mudou pra muito melhor. Tanto na parte pessoal, quanto profissional.</p>
                <div class="client-info">
                  <img src="<%= image_path('testimonial/duque-icon.png') %>" />
                  <h4 style="color: #fff;">Rodrigo Duque, 26 anos</h4>
                  <span style="color: #fff;">Advogado</span>
                </div>
              </div><!-- /.item -->
              <div class="item">
                <p class="speech">Difícil falar sem se emocionar. Eu acho que essa obra é uma grande prova dos milagres, carinho e amor de Deus. Porque, é de fato, uma experiência única que muda vidas inteiras.</p>
                <div class="client-info">
                  <img src="<%= image_path('testimonial/annie-icon.png') %>" />
                  <h4 style="color: #fff;">Annie Lattari, 32 anos</h4>
                  <span style="color: #fff;">Jornalista</span>
                </div>
              </div><!-- /.item -->
            </div><!-- /.client-testimonials -->
          </div><!-- /.col-md-8 -->
        </div><!-- /.row -->
      </div><!-- /.container -->
    </div><!-- /.row -->
  </div><!-- /.container -->
</section><!-- /#testimonials -->

app/views/welcome/index.html.erb
<%= render partial: 'menu' %>

<%= render partial: 'welcome' %>

<%= render partial: 'about_us' %>

<%= render partial: 'missions' %>

<%= render partial: 'counter' %>

<%= render partial: 'protector' %>

<%= render partial: 'parish' %>

<%= render partial: 'sponsors' %>

<%# render partial: 'testimonials' %>

<%= render partial: 'footer' %>

<%= javascript_include_tag "hallooou" %>
<!-- Google Analytics -->
<%= javascript_include_tag "google_analytics" %>

<!-- Google Maps - Required by Hallooou JS -->
<script src="https://maps.googleapis.com/maps/api/js"></script>

<%# render partial: 'team' %>
<%# render partial: 'products' %>
<%# render partial: 'portfolio' %>
<%# render partial: 'testimonials' %>
<%# render partial: 'call_to_action_I' %>
<%# render partial: 'call_to_action_II' %>
<%# render partial: 'contact' %>